config/routes.rb
Rails.application.routes.draw do  
  root 'projects#index'

  resources :projects do
    post 'ajax_video_update'
    post 'ajax_image_update_on_recording'    
    post 'ajax_videometadata_update'
    resources :videos do
      resources :snapshots
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :project  
  has_many :snapshots
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @project =  Project.find params[:project_id]
    @videos = @project.videos
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @project =  Project.find params[:project_id]    
  end

  # GET /videos/new
  def new
    @project =  Project.find params[:project_id]
    @video = Video.new     
    @video.project @project
  end


  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to project_video_path, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :description, :project_id, :video, :meters)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div>
    <label for="video-width">Video Width:</label>
    <input type="text" id="video-width" value="320">
    <label for="video-height">Video Height:</label>
    <input type="text" id="video-height" value="240">
    <button id="start-recording"  class="btn btn-success" >Start Recording</button>
    <button id="stop-recording" class="btn btn-danger" disabled>Stop Recording</button>
    <button id="snapshot_on_recording" class="btn btn-primary" disabled>Snapshot</button>
</div>
    <div id="videos-container"></div>
    <div id="uploaded-videos-container"></div>

<script type="text/javascript">

//Global variables
var url_ajax = "<%= project_ajax_video_update_path %>"
var url_image_on_recording_ajax = "<%= project_ajax_image_update_on_recording_path %>"
var url_video_metadata_ajax = "<%= project_ajax_videometadata_update_path %>"
var videos_container = document.getElementById('videos-container');
var uploaded_videos_container = document.getElementById('uploaded-videos-container');
//buttons controller
document.querySelector('#snapshot_on_recording').onclick = function() {
    var v = document.getElementsByTagName('video')[0];
    var c = capture(v);
    var current_time = v.currentTime;
    var dataURI = c.toDataURL('image/jpeg'); // can also use 'image/png'
    var img = document.createElement('img');
    var form_data = new FormData();

    img.src = dataURI;
    uploaded_videos_container.appendChild(img);    
    form_data.append('image-filename', 'snapshot');
    form_data.append('image-image', dataURI);
    form_data.append('video_id', 0);
    form_data.append('current_time', current_time);
    sendImageAjax(url_image_on_recording_ajax, form_data, function (fileURL) {
    });
}

document.querySelector('#start-recording').onclick = function() {
    this.disabled = true;
    document.querySelector('#stop-recording').disabled = false;
    document.querySelector('#snapshot_on_recording').disabled = false;
    navigator.getUserMedia(media_constraints, onMediaSuccess, onMediaError);
};

document.querySelector('#stop-recording').onclick = function() {
    this.disabled = true;   
    media_recorder.stop();
    document.querySelector('#start-recording').disabled = false;
    document.querySelector('#snapshot_on_recording').disabled = true;
    //delete video element
    var v = document.getElementsByTagName('video');
    v = document.querySelector('#video-player');
    videos_container.removeChild(v);
    //deleted    
};
</script>

app/views/videos/edit.html.erb
<div class="page-header">
  <%= link_to project_video_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to project_video_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Edit Video metadata</h1>
</div>

<%= simple_form_for @video, 
    url: project_video_path,
    method: 'PATCH'  do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :meters %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Video Recording using MediaStreamRecorder</h1>
</div>

<%= render 'form' %>

app/views/videos/show.html.erb
<div class="page-header">
  <%= link_to project_path(@project), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
<%= link_to edit_project_video_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Edit metadata
  <% end %>

  <h1>Show video</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @video.name %></dd>

  <dt>Description:</dt>
  <dd><%= @video.description %></dd>

  <dt>Project:</dt>
  <dd><%= @video.project %></dd>

  <dt>Meters:</dt>
  <dd><%= @video.meters %></dd>

  <dt>amount of snapshots:</dt>
  <dd><%= @video.snapshots.count %></dd>

  <dt>Video:</dt>
  <video width= "<%=@video.width%>" height= "<%=@video.height%>" controls>
  <source src="<%= @video.file %>" type="video/webm">
  Your browser does not support the video tag.
  </video>
  <button id="snapshot" class="btn btn-primary" disabled >Snapshot</button>

<hr>


<div id='snapshots-container'>
  <% @video.snapshots.each do |snapshot| %>
    <%= link_to edit_project_video_snapshot_path(@video.project, @video, snapshot ) do %>  
      <img src="/videos/<%= snapshot.file %>.jpg" alt="snapshot.name" height="<%= snapshot.video.height%>" width="<%= snapshot.video.width %>">      
    <% end %>
    Description:
      <span> <%= snapshot.description %> </span>
<% end %>
  

</div>




</dl>