config/routes.rb
Rails.application.routes.draw do  
  root 'projects#index'

  resources :projects do
    post 'ajax_video_update'
    post 'ajax_image_update_on_recording'    
    post 'ajax_videometadata_update'
    resources :videos do
      resources :snapshots
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :videos
	def to_s
	  name
	end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def ajax_videometadata_update
    video = Video.find(params[:hiden_video_id])
    video.meters = params[:meters]
    video.name = params[:name]
    video.description = params[:description]
    video.save    
    respond_to do |format|
      format.js { render nothing: :true }
    end
  end

  def ajax_video_update
    #esta funcion Crea o asigna los valores a un vide
    #trabaja en conjunto con ajax_image_update_on_recording
    #ambas funcones utilizan video_id dentro de la session del usuario
    project = Project.find params[:project_id]
    video = params[:'video-blob']
    # esto es proque si la session existe el video ya esta creado, y sino existe se crea despues!
    video_count = (session.has_key?("video_id")) ? project.videos.count : project.videos.count + 1
    save_path = Rails.root.join("public/videos")
    video_name = "project_#{project.name}_video_#{video_count}"

    File.open("#{save_path}/#{video_name}", 'wb') do |f|
      f.write video.read
    end

    # Chekeamos si el video ya existe por un snapshot!
    if session.has_key?("video_id")       
      video = Video.find(session[:video_id])
      video.file = "/videos/#{video_name}"
      video.name = video_name
      video.width = params[:width]
      video.height = params[:height]
      video.save
      session.delete(:video_id)
    else
      project.videos.create project: project, file: "/videos/#{video_name}", name: video_name, width: params[:width], height: params[:height]
    end    
    #este valor es para el form que luego actualiza la metadata!
    video_id = project.videos.last.id
    respond_to do |format|
      format.json { render :json => { :video_id => video_id } }
    end
  end

  
  def ajax_image_update_on_recording
    #Esta funcion crea un objeto video mientas se esta grabando
    #para asignar los snapshots al mismo
    #trabaja en conjunto con ajax_video_update
    #ambas funcones utilizan video_id dentro de la session del usuario
    project = Project.find params[:project_id]
    #chekear si video_id ya existe en la session para no crear mas de un video por todos los snapshots!
    if session.has_key?("video_id")    
      video = Video.find(session[:video_id])   
    else
      video = project.videos.create project: project 
      session[:video_id] = video.id
    end
        
    image = params[:'image-image']
    video_time = params[:current_time]
    snapshot_count = video.snapshots.count + 1
    save_path = Rails.root.join("public/videos")
    image_name = "project_#{project.id}_video_#{video.id}_snapshot_#{snapshot_count}"

    File.open("#{save_path}/#{image_name}.jpg", 'wb') do |f|
      f.write(Base64.decode64(image['data:image/jpeg;base64,'.length .. -1]))
    end
    #creamos el objeto snapshot!
    video.snapshots.create video: video, file: image_name, time: video_time
    respond_to do |format|
      format.js { render nothing: :true }
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show    
    @project = Project.find params[:id]
    @videos = @project.videos
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :begin, :end, :place)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :date %>  
    <%= f.input :place %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @project, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <%= link_to new_project_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Project
  <% end %>
  <h1>Listing projects</h1>
</div>

<div>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
            <th>Place</th>
            <th>Actions</th>
        
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @projects) do |project| %>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.date %></td>
            <td><%= project.place %></td>
            <td>
                <!-- Single button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    Action <span class="caret"></span>
                  </button>
                <ul class="dropdown-menu" role="menu">
                    <li class="divider"></li>
                    <li><%= link_to 'Show', project %></li>
                    <li class="divider"></li>
                    <li><a>Export to pdf </a></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Edit', edit_project_path(project) %></li>    
                    <li class="divider"></li>
                    <li><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  </ul>
                </div>
            </td>
        
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>

<%= link_to  new_project_video_path(@project), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    New Video
  <% end %>


  <h1>Show project</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @project.name %></dd>

  <dt>Description:</dt>
  <dd><%= @project.description %></dd>

  <dt>Date:</dt>
  <dd><%= @project.date %></dd>

  <dt>Place:</dt>
  <dd><%= @project.place %></dd>

</dl>

<!-- ######################## -->
<div class="page-header">  
  <h1>Listing videos from project <%= @project %></h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Meters</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @videos) do |video| %>
            <td><%= video.name %></td>
            <td><%= video.description %></td>
            <td><%= video.meters %></td>
            <td><%= link_to 'Show', project_video_path(@project, video), class: "btn btn-info" %>
        <%= link_to 'Edit Metadata', edit_project_video_path(@project, video), class: "btn btn-primary"  %>
            </td>
      <% end %>
    </tbody>
  </table>
</div>