config/routes.rb
Rails.application.routes.draw do  
  root 'projects#index'

  resources :projects do
    post 'ajax_video_update'
    post 'ajax_image_update_on_recording'    
    post 'ajax_videometadata_update'
    resources :videos do
      resources :snapshots
    end
  end

end

app/models/snapshot.rb
class Snapshot < ActiveRecord::Base
  belongs_to :video
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :set_snapshot, only: [:show, :edit, :update, :destroy]

  # GET /snapshots
  # GET /snapshots.json
  def index
    @snapshots = Snapshot.all
  end

  # GET /snapshots/1
  # GET /snapshots/1.json
  def show
  end

  # GET /snapshots/new
  def new
    @snapshot = Snapshot.new
  end

  # GET /snapshots/1/edit
  def edit
  end

  # POST /snapshots
  # POST /snapshots.json
  def create
    @snapshot = Snapshot.new(snapshot_params)

    respond_to do |format|
      if @snapshot.save
        format.html { redirect_to @snapshot, notice: 'Snapshot was successfully created.' }
        format.json { render :show, status: :created, location: @snapshot }
      else
        format.html { render :new }
        format.json { render json: @snapshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snapshots/1
  # PATCH/PUT /snapshots/1.json
  def update
    respond_to do |format|
      if @snapshot.update(snapshot_params)
        format.html { redirect_to project_video_path, notice: 'Snapshot was successfully updated.' }
        format.json { render :show, status: :ok, location: @snapshot }
      else
        format.html { render :edit }
        format.json { render json: @snapshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snapshots/1
  # DELETE /snapshots/1.json
  def destroy
    video = @snapshot.video
    project = video.project
    @snapshot.destroy
    respond_to do |format|
      format.html { redirect_to project_video_path(project,video ), notice: 'Snapshot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snapshot
      @snapshot = Snapshot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snapshot_params
      params.require(:snapshot).permit(:name, :description, :video_id, :file)
    end
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/views/snapshots/_form.html.erb
<%= simple_form_for @snapshot, 
    url: project_video_snapshot_path,
    method: 'PATCH'  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/snapshots/edit.html.erb
<div class="page-header">
  <%= link_to project_video_path(@snapshot.video.project,@snapshot.video), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to project_video_snapshot_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Delete
  <% end %>
  <h1>Editing snapshot</h1>
</div>

<%= render 'form' %>

app/views/snapshots/index.html.erb
<div class="page-header">
  <%= link_to new_snapshot_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Snapshot
  <% end %>
  <h1>Listing snapshots</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Video</th>
            <th>File</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @snapshots) do |snapshot| %>
            <td><%= snapshot.name %></td>
            <td><%= snapshot.description %></td>
            <td><%= snapshot.video %></td>
            <td><%= snapshot.file %></td>
            <td><%= link_to 'Show', snapshot %></td>
        <td><%= link_to 'Edit', edit_snapshot_path(snapshot) %></td>
        <td><%= link_to 'Destroy', snapshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/snapshots/new.html.erb
<div class="page-header">
  <%= link_to snapshots_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New snapshot</h1>
</div>

<%= render 'form' %>

app/views/snapshots/show.html.erb
<div class="page-header">
  <%= link_to snapshots_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_snapshot_path(@snapshot), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show snapshot</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @snapshot.name %></dd>

  <dt>Description:</dt>
  <dd><%= @snapshot.description %></dd>

  <dt>Video:</dt>
  <dd><%= @snapshot.video %></dd>

  <dt>File:</dt>
  <dd><%= @snapshot.file %></dd>

</dl>